### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by damirmur** [craigbuckler/asayer-idbstate#1]
Access to script at 'file:///D:/Users/dmyr/Documents/GitHub/asayer-idbstate/js/main.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.

**Comment by craigbuckler** [comment]
It looks as though you're attempting to open the files over your file system rather than running a web server. See the README for more information.

**Comment by damirmur** [comment]
Made it work without a web server.
index.html changed:
<script src="js/components/todo-add.js"></script>
<script src="js/components/todo-list.js"></script>
<script src="js/lib/state.js"></script>
<script src="js/lib/indexeddb.js"></script>
remove main.js
Removed in scripts from export, import.

**Comment by craigbuckler** [comment]
OK, but I still recommend you use a web server!

**Comment by gorod0k** [comment]
> Made it work without a web server. index.html changed:
> 
> <script src="js/components/todo-add.js"></script> <script src="js/components/todo-list.js"></script> <script src="js/lib/state.js"></script> <script src="js/lib/indexeddb.js"></script>
> remove main.js Removed in scripts from export, import.

Great comment!
 The server is superfluous for just the client example
